(() => {
"use strict";
const field=document.getElementById("fieldCanvas"),fctx=field.getContext("2d");
const bouquet=document.getElementById("bouquetCanvas"),bctx=bouquet.getContext("2d");
const fieldScene=document.getElementById("fieldScene"),bouquetScene=document.getElementById("bouquetScene");
const intro=document.getElementById("intro"),enter=document.getElementById("enter"),reset=document.getElementById("reset"),back=document.getElementById("back");
const count=document.getElementById("count"),infoList=document.getElementById("infoList");
const message=document.getElementById("message"),closeMessage=document.getElementById("closeMessage"),messageTitle=document.getElementById("messageTitle"),messageBody=document.getElementById("messageBody");
const DPR=1.7,TARGET=7;
const flowerMeta=[
{name:"Lirio rojo",kind:"red",note:"Intensidad y amor profundo.",message:"Tu manera de amar tiene una fuerza que se queda conmigo."},
{name:"Lirio blanco",kind:"white",note:"Calma y ternura silenciosa.",message:"Hay una paz especial en la forma en que cuidas a quienes quieres."},
{name:"Lirio degradado",kind:"gradient",note:"Dulzura y fuerza.",message:"En ti pueden existir al mismo tiempo la delicadeza y una fuerza inmensa."},
{name:"Lirio rojo intenso",kind:"red",note:"Una forma de amar verdadera.",message:"Cuando amas, lo haces con una profundidad que se siente incluso en los silencios."},
{name:"Lirio blanco puro",kind:"white",note:"Serenidad y refugio.",message:"Tu presencia puede sentirse como un lugar tranquilo al que siempre dan ganas de volver."},
{name:"Lirio rosado",kind:"gradient",note:"Ternura y sensibilidad.",message:"Tu ternura aparece en detalles pequeños que terminan significándolo todo."},
{name:"Lirio especial",kind:"gradient",note:"Todas tus formas de querer.",message:"No eres una sola flor: eres el jardín entero que aparece cuando alguien aprende a conocerte."}
];
const S={started:false,scene:"field",w:0,h:0,bw:0,bh:0,time:0,last:performance.now(),selected:[],flowers:[],pollen:[],bpollen:[],hits:[]};
const images={};
const paths=[];
for(const kind of ["white","red","gradient"])for(let i=1;i<=5;i++)paths.push([`${kind}${i}`,`assets/lily_${kind}_${i}.png`]);
let loaded=0;
for(const [k,p] of paths){const im=new Image();im.src=p;im.onload=()=>loaded++;images[k]=im}
function fit(c,ctx){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,DPR);c.width=Math.floor(r.width*d);c.height=Math.floor(r.height*d);ctx.setTransform(d,0,0,d,0,0);return{w:r.width,h:r.height}}
function resize(){const a=fit(field,fctx),b=fit(bouquet,bctx);S.w=a.w;S.h=a.h;S.bw=b.w;S.bh=b.h;buildFlowers()}
function buildFlowers(){S.flowers=[];const w=S.w,h=S.h;const positions=[[.16,.78,.95],[.29,.66,.82],[.41,.82,1.02],[.53,.61,.78],[.64,.76,.94],[.77,.64,.82],[.87,.82,1.0]];positions.forEach((p,i)=>S.flowers.push({i,x:w*p[0],y:h*p[1],scale:p[2],kind:flowerMeta[i].kind,img:(i%5)+1,selected:S.selected.some(q=>q.i===i),phase:i*.9}))}
function drawStars(){const w=S.w,h=S.h;fctx.save();for(let i=0;i<95;i++){const x=(i*83.17)%w,y=(i*47.31)%(h*.33),a=.18+((i%7)/7)*.55;fctx.fillStyle=`rgba(220,234,255,${a})`;fctx.beginPath();fctx.arc(x,y,.45+(i%3)*.35,0,Math.PI*2);fctx.fill()}fctx.restore()}
function drawMoon(){const x=S.w*.22,y=S.h*.13,r=Math.min(S.w,S.h)*.055;let q=fctx.createRadialGradient(x,y,0,x,y,r*3.2);q.addColorStop(0,"rgba(245,249,255,.55)");q.addColorStop(.3,"rgba(164,193,235,.13)");q.addColorStop(1,"rgba(120,160,220,0)");fctx.fillStyle=q;fctx.beginPath();fctx.arc(x,y,r*3.2,0,Math.PI*2);fctx.fill();q=fctx.createRadialGradient(x-r*.3,y-r*.3,0,x,y,r);q.addColorStop(0,"#fffef8");q.addColorStop(.65,"#dae4ef");q.addColorStop(1,"#8396aa");fctx.fillStyle=q;fctx.beginPath();fctx.arc(x,y,r,0,Math.PI*2);fctx.fill()}
function drawDecor(){// lirios araña y lirios del valle discretos al fondo
 const h=S.h,w=S.w;
 fctx.save();fctx.globalAlpha=.34;
 for(let i=0;i<36;i++){const x=(i*97.3)%w,y=h*(.44+((i*31)%40)/100),r=2+((i%5)*.35);fctx.strokeStyle=i%2?"#7aa8ff":"#b52643";fctx.lineWidth=.7;for(let j=0;j<6;j++){const a=j*Math.PI/3;fctx.beginPath();fctx.moveTo(x,y);fctx.quadraticCurveTo(x+Math.cos(a+.4)*r*4,y+Math.sin(a+.4)*r*4,x+Math.cos(a)*r*8,y+Math.sin(a)*r*8);fctx.stroke()}}
 fctx.globalAlpha=.38;for(let i=0;i<44;i++){const x=(i*71.1)%w,y=h*(.5+((i*19)%36)/100);fctx.fillStyle="#edf4ea";for(let j=0;j<4;j++){fctx.beginPath();fctx.arc(x+(j%2?4:-4),y-j*4,1.6,0,Math.PI*2);fctx.fill()}}
 fctx.restore()}
function drawPhotoFlower(ctx,fl,bouq=false){const key=`${fl.kind}${fl.img}`,im=images[key];if(!im||!im.complete)return null;const sway=bouq?Math.sin(S.time*.001+fl.phase)*1.2:Math.sin(S.time*.0013+fl.phase)*(2+fl.scale*2);const size=(bouq?120:150)*fl.scale;const x=fl.x+sway,y=fl.y;ctx.save();ctx.globalAlpha=bouq?1:.98;if(!bouq&&!fl.selected){const pulse=.7+Math.sin(S.time*.003+fl.phase)*.18;const q=ctx.createRadialGradient(x,y,0,x,y,size*.52);q.addColorStop(0,`rgba(255,238,190,${.25*pulse})`);q.addColorStop(.48,`rgba(244,90,112,${.12*pulse})`);q.addColorStop(1,"rgba(255,255,255,0)");ctx.fillStyle=q;ctx.beginPath();ctx.arc(x,y,size*.52,0,Math.PI*2);ctx.fill()}ctx.drawImage(im,x-size/2,y-size/2,size,size);ctx.restore();return{x,y,r:size*.33}}
function spawn(x,y,strong=false,bouq=false){const list=bouq?S.bpollen:S.pollen,n=strong?55:28;for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,v=.35+Math.random()*(strong?2.2:1.2);list.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v-.6,life:700+Math.random()*700,r:.8+Math.random()*1.8})}}
function particles(ctx,list,dt){for(let i=list.length-1;i>=0;i--){const p=list[i];p.life-=dt;if(p.life<=0){list.splice(i,1);continue}p.vy+=.009;p.x+=p.vx*dt/16.7;p.y+=p.vy*dt/16.7;const a=Math.min(1,p.life/350);ctx.shadowBlur=8;ctx.shadowColor="rgba(255,211,116,.9)";ctx.fillStyle=`rgba(255,220,137,${a})`;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}}
function renderField(dt){fctx.clearRect(0,0,S.w,S.h);drawStars();drawMoon();drawDecor();for(const fl of S.flowers)if(!fl.selected)drawPhotoFlower(fctx,fl,false);particles(fctx,S.pollen,dt)}
function bouquetLayout(){const sc=Math.max(.72,Math.min(1.15,Math.min(S.bw*.5,S.bh*.76)/430));return{cx:S.bw*(S.bw<800?.45:.47),by:S.bh*.84,sc,pos:[[-86,-8,.88,-.18],[-56,-52,.94,-.12],[-26,-20,.92,-.06],[0,-88,1.04,0],[28,-20,.92,.06],[58,-52,.94,.12],[88,-8,.88,.18]]}}
function bouquetBg(){const w=S.bw,h=S.bh;let q=bctx.createLinearGradient(0,0,0,h);q.addColorStop(0,"#07101c");q.addColorStop(.58,"#080810");q.addColorStop(1,"#170a11");bctx.fillStyle=q;bctx.fillRect(0,0,w,h);for(let i=0;i<100;i++){const x=(i*91.3)%w,y=(i*43.7)%h,a=.05+((i%8)/8)*.16;bctx.fillStyle=`rgba(225,236,255,${a})`;bctx.beginPath();bctx.arc(x,y,.5+(i%3)*.3,0,Math.PI*2);bctx.fill()}}
function wrapBack(L){const s=L.sc;bctx.save();bctx.translate(L.cx,L.by);bctx.fillStyle="rgba(211,184,154,.76)";for(const side of [-1,1]){bctx.beginPath();bctx.moveTo(side*30*s,90*s);bctx.lineTo(side*145*s,-110*s);bctx.lineTo(side*55*s,-70*s);bctx.lineTo(0,78*s);bctx.closePath();bctx.fill()}bctx.fillStyle="rgba(237,218,196,.45)";for(const side of [-1,1]){bctx.beginPath();bctx.moveTo(side*18*s,82*s);bctx.lineTo(side*92*s,-145*s);bctx.lineTo(side*18*s,-82*s);bctx.lineTo(0,70*s);bctx.closePath();bctx.fill()}bctx.restore()}
function wrapFront(L){const s=L.sc;bctx.save();bctx.translate(L.cx,L.by);let q=bctx.createLinearGradient(-70*s,-20*s,70*s,130*s);q.addColorStop(0,"#ddc2a7");q.addColorStop(.55,"#a77b5f");q.addColorStop(1,"#65483b");bctx.fillStyle=q;bctx.beginPath();bctx.moveTo(-72*s,-28*s);bctx.quadraticCurveTo(-50*s,36*s,-31*s,128*s);bctx.lineTo(31*s,128*s);bctx.quadraticCurveTo(50*s,36*s,72*s,-28*s);bctx.quadraticCurveTo(0,5*s,-72*s,-28*s);bctx.closePath();bctx.fill();bctx.fillStyle="#76182f";bctx.beginPath();bctx.ellipse(0,35*s,60*s,14*s,0,0,Math.PI*2);bctx.fill();bctx.fillStyle="#a63851";for(const side of [-1,1]){bctx.beginPath();bctx.moveTo(side*5*s,33*s);bctx.bezierCurveTo(side*48*s,7*s,side*72*s,45*s,side*22*s,58*s);bctx.bezierCurveTo(side*45*s,82*s,side*8*s,86*s,-side*7*s,46*s);bctx.fill()}bctx.restore()}
function renderBouquet(dt){bouquetBg();const L=bouquetLayout();S.hits=[];wrapBack(L);for(let i=0;i<S.selected.length;i++){const src=S.selected[i],p=L.pos[i],fl={...src,x:L.cx+p[0]*L.sc,y:L.by+p[1]*L.sc,scale:p[2]*L.sc,phase:i*.7};bctx.strokeStyle="rgba(65,108,56,.85)";bctx.lineWidth=3*L.sc;bctx.beginPath();bctx.moveTo(L.cx,L.by+20*L.sc);bctx.quadraticCurveTo(fl.x,L.by-60*L.sc,fl.x,fl.y+55*L.sc);bctx.stroke();const hit=drawPhotoFlower(bctx,fl,true);if(hit)S.hits.push({...hit,i:src.i})}wrapFront(L);particles(bctx,S.bpollen,dt)}
function hitField(x,y){let best=null,bd=1e9;for(const fl of S.flowers){if(fl.selected)continue;const d=Math.hypot(x-fl.x,y-fl.y),r=55*fl.scale;if(d<r&&d<bd){best=fl;bd=d}}return best}
function onField(e){if(!S.started||S.scene!=="field")return;const r=field.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,fl=hitField(x,y);if(!fl){spawn(x,y);return}spawn(fl.x,fl.y,true);fl.selected=true;S.selected.push({...fl});count.textContent=S.selected.length;if(S.selected.length===TARGET)setTimeout(openBouquet,800)}
function onBouquet(e){if(S.scene!=="bouquet"||!message.classList.contains("hidden"))return;const r=bouquet.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let hit=null,bd=1e9;for(const h of S.hits){const d=Math.hypot(x-h.x,y-h.y);if(d<h.r&&d<bd){hit=h;bd=d}}if(!hit)return;spawn(hit.x,hit.y,true,true);const m=flowerMeta[hit.i];messageTitle.textContent=m.name;messageBody.textContent=m.message;message.classList.remove("hidden")}
function fillInfo(){infoList.innerHTML="";for(const fl of S.selected){const m=flowerMeta[fl.i],item=document.createElement("div");item.className="info-item";const sw=document.createElement("div");sw.className="swatch";sw.style.background=m.kind==="white"?"radial-gradient(circle,#fffef8,#d7e0e5)":m.kind==="red"?"radial-gradient(circle,#ffd4c8,#ce304b 55%,#6d091c)":"radial-gradient(circle,#fff5ed,#df7887 55%,#7d1029)";const tx=document.createElement("div"),st=document.createElement("strong"),sp=document.createElement("span");st.textContent=m.name;sp.textContent=m.note;tx.append(st,sp);item.append(sw,tx);infoList.append(item)}}
function openBouquet(){fillInfo();S.scene="bouquet";fieldScene.classList.add("hidden");bouquetScene.classList.remove("hidden")}
function openField(){S.scene="field";bouquetScene.classList.add("hidden");fieldScene.classList.remove("hidden")}
function resetAll(){S.selected=[];S.pollen=[];S.bpollen=[];count.textContent="0";message.classList.add("hidden");openField();buildFlowers()}
function loop(now){const dt=Math.min(40,now-S.last);S.last=now;S.time=now;renderField(dt);renderBouquet(dt);requestAnimationFrame(loop)}
enter.addEventListener("click",()=>{S.started=true;intro.classList.add("hidden")});reset.addEventListener("click",resetAll);back.addEventListener("click",openField);field.addEventListener("pointerdown",onField);bouquet.addEventListener("pointerdown",onBouquet);closeMessage.addEventListener("click",()=>message.classList.add("hidden"));addEventListener("resize",resize,{passive:true});resize();requestAnimationFrame(loop);
})();